server:
   port: 8066
spring:
   application: 
      name: zuulserver
   zipkin:
    enabled: true
    base-url: http://localhost:9411/

     

zuul:
 routes:
   userservice:
      path: /user-service/**
      url: http://localhost:8068/   
   adminservice:
      path: /admin-service/**
      url: http://localhost:8067/
   sampleservice:
      path: /sample-service/**
      url: http://localhost:8069/

     

eureka:
 client:
   serviceUrl:
       defaultZone : http://localhost:8065/eureka
       registerWithEureka: false
       fetchRegistry : true
       
       
       